
R Under development (unstable) (2024-11-13 r87325) -- "Unsuffered Consequences"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> # This file is part of the standard setup for testthat.
> # It is recommended that you do not modify it.
> #
> # Where should you do additional test configuration?
> # Learn more about the roles of various files in:
> # * https://r-pkgs.org/testing-design.html#sec-tests-files-overview
> # * https://testthat.r-lib.org/articles/special-files.html
> 
> require(testthat)
Loading required package: testthat
> require(PvSTATEM)
Loading required package: PvSTATEM
> 
> test_check("PvSTATEM")
Creating the output directory: '/var/scratch2/tomas/tmp/Rtmps41kQy/output'
([31mWARNING[39m)
Using less than five samples to fit the logistic model. For now, using the basic nplr method to fit the logistic model - should be modified in the futureInstance of the Model class fitted for analyte ' Spike_6P_IPP ': 
 - fitted with 2 parameters
 - using 2 samples
 - using log residuals (mfi):  TRUE 
 - using log dilution:  TRUE 
 - top asymptote: 100 
 - bottom asymptote: 50 
 - goodness of fit: 1 
 - weighted goodness of fit: 1 
[1] "Parsing file/var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/external/Chul_IgG3_1.csv"
[1] "Parsing successful"
[1] "Parsing file/var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/external/Chul_TotalIgG_2.csv"
[1] "Parsing successful"
[1] "Parsing file/var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/external/New_Batch_14_20140513_082522.csv"
[1] "Parsing successful"
[1] "Parsing file/var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/external/New_Batch_6_20160309_174224.csv"
[1] "Parsing successful"
[1] "Parsing file/var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/external/pone.0187901.s001.csv"
[1] "Parsing successful"
Reading Luminex data from: /var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/CovidOISExPONTENT_CO.csv
using format xPONENT
([31mWARNING[39m)
Number of layout fields is higher than the number of samples. Please check the layout file. Using only first 49 dilutions from the layout file. 
[32m
New plate object has been created with name: CovidOISExPONTENT_CO!
[39m
Reading Luminex data from: /var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/CovidOISExPONTENT_CO.csv
using format xPONENT
([31mWARNING[39m)
Number of layout fields is higher than the number of samples. Please check the layout file. Using only first 49 dilutions from the layout file. 
[32m
New plate object has been created with name: CovidOISExPONTENT_CO!
[39m
Reading Luminex data from: /var/scratch2ro/tomas/cran/rlibro/lib/PvSTATEM/extdata/CovidOISExPONTENT_CO.csv
using format xPONENT
([31mWARNING[39m)
Number of layout fields is higher than the number of samples. Please check the layout file. Using only first 49 dilutions from the layout file. 
[32m
New plate object has been created with name: CovidOISExPONTENT_CO!
[39m
Fitting the models and predicting RAU for each analyte
Adding the raw MFI values to the output dataframe
Saving the computed RAU values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
Fitting the models and predicting RAU for each analyte
Adding the raw MFI values to the output dataframe
Saving the computed RAU values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
Fitting the models and predicting RAU for each analyte
Computing nMFI values for each analyte
Adding the raw MFI values to the output dataframe
Saving the computed nMFI values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
Computing nMFI values for each analyte
Adding the raw MFI values to the output dataframe
Saving the computed nMFI values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
Computing nMFI values for each analyte
Computing nMFI values for each analyte
Computing nMFI values for each analyte
Computing nMFI values for each analyte
Saving the computed nMFI values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
Computing nMFI values for each analyte
Adding the raw MFI values to the output dataframe
Saving the computed nMFI values to a CSV file located in: '/var/scratch2/tomas/tmp/Rtmps41kQy/output.csv'
[ FAIL 7 | WARN 12 | SKIP 0 | PASS 218 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-generate_report.R:33:3'): Test generate_plate_report function ──
Expected `generate_plate_report(plate, output_dir = tmp_dir)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:34:3'): Test generate_plate_report function ──
Expected `generate_plate_report(plate, output_dir = tmp_dir, filename = "test_report.html")` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:36:3'): Test generate_plate_report function ──
Expected `generate_plate_report(...)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:38:3'): Test generate_plate_report function ──
Expected `generate_plate_report(...)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:43:3'): Test generate_plate_report function ──
Expected `generate_plate_report(...)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:53:3'): Test generate_levey_jennings_report function ──
Expected `generate_levey_jennings_report(list(plate), output_dir = tmp_dir)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection
── Failure ('test-generate_report.R:54:3'): Test generate_levey_jennings_report function ──
Expected `generate_levey_jennings_report(...)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  cannot open the connection

[ FAIL 7 | WARN 12 | SKIP 0 | PASS 218 ]
Error: Test failures
Execution halted
